###
POST http://localhost:3000/signup
Content-Type: application/json

{
 "Firstname":"ifeoluwa",
 "Lastname":"blessing",
 "Dateofbirth":"2002-10-06",
 "EmailAddress":"kene100@gmail.com",
 "Pass":"1234meclll" 
}

###
GET http://localhost:3000/login
Content-Type: application/json

{
    "EmailAddress":"kennedymarvellous1@gmail.com",
    "Pass":"1234marve"
} 

###
GET http://localhost:3000/getuser/id

###
POST http://localhost:3000/createpost/:2
Content-Type: application/json

{
    "title":"hello",
    "content":"this is a content"
}

###
PUT http://localhost:3000/updatepost/2
Content-Type: application/json

{
    "title":"my tittle",
    "content":"this is my content"
}

###
DELETE http://localhost:3000/deletepost/:1
Content-Type: application/json

{
    "title":"my tittle",
    "content":"this is my content"

}

###
POST http://localhost:3000/posts/2/comments
Content-Type: application/json

{ 
    "content":"This is a comment."
}

###
POST http://localhost:3000/posts/2/like
Content-Type: application/json

{
    "user_id":1
}

###
GET http://localhost:3000/posts/:post_id/like/count
Content-Type: application/json

###
POST http://localhost:3000/messages/send
Content-Type: application/json

{
 "sender_id": 1,
 "receiver_id": 2,
 "message": "Hello, this is a test message."
}

###
POST http://localhost:3000/messages/send
Content-Type: application/json

{
 "sender_id": 2,
 "receiver_id": 1,
 "message": "Hello, this is a test message."
}