### endpoint for signup
POST http://localhost:4000/signup
Content-Type: application/json

{
 "Firstname":"udeh",
 "Lastname":"marvellous",
 "Dateofbirth":"2006-11-03",
 "EmailAddress":"developermarvellous001@gmail.com",
 "Pass":"kenny001" 
}

### endpoint for login
GET http://localhost:4000/login
Content-Type: application/json

{
    "EmailAddress":"kennedymarvellous1@gmail.com",
    "Pass":"1234marve"
} 

### endpoint for getting usrs by id 
GET http://localhost:4000/getuser/:id

### endpoint for creating posts
POST http://localhost:4000/createpost/:2
Content-Type: application/json

{
    "title":"hello",
    "content":"this is a content"
}

### endpoint for getting post by id 
GET http://localhost:4000/getpost/2

### endpoint for updating posts
PUT http://localhost:4000/updatepost/2
Content-Type: application/json

{
    "title":"holy beast",
    "content":"this is my content"
}

### endpoint for deleting posts
DELETE http://localhost:4000/deletepost/:1
Content-Type: application/json

{
    "title":"my tittle",
    "content":"this is my content"

}

### endpoint for coomenting on posts by id 
POST http://localhost:4000/posts/2/comments
Content-Type: application/json

{ 

    "message":"This is a comment."
}

### endpoint for liking posts by id 
POST http://localhost:4000/posts/2/like
Content-Type: application/json

{
    "user_id":1
}

### endpoint for getting all like count by id 
GET http://localhost:4000/posts/2/like/count
Content-Type: application/json

### endpoint for getting all comment counts by id 
GET http://localhost:4000/TotalCommentCount/2

### endpoint for sending messages
POST http://localhost:4000/messages/send
Content-Type: application/json

{
 "sender_id": 1,
 "receiver_id": 2,
 "message": "Hello, this is a test message."
}

###endpoint for getting mesages of two users
GET http://localhost:4000/get-messages/1/2
Content-Type: application/json

### endpoint for sending an otp
POST http://localhost:4000/send-otps
Content-Type: application/json

{
    "email":"tomiwamonehin@gmail.com"
}

### providing an endpoint for getting  both the like count and the comment count
GET http://localhost:4000/posts/2/counts
Content-Type: application/json

### using JOIN method to provide  an endpoint for getting  both the like count and the comment count
GET http://localhost:4000/posts/2/like,comment/count
Content-Type: application/json